In [2]:
import numpy as np

In [4]:
A = np.asarray([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
A.shape

(3, 2)

* $A \in R^{3 \times 2}$

  $A$ is a matrix of
  * 3 rows
  * 2 columns

If I want the first column of A, I expect:

* $A_{1} \in R^{3\times1}$

But numpy removes unitary dimensions:

In [7]:
print(A[:,0])
A[:,0].shape

[1 3 5]


(3,)

So I don't have a matrix anymore.

using `np.newaxis` can solve this

In [9]:
print(A[:,0, np.newaxis])
A[:,0, np.newaxis].shape

[[1]
 [3]
 [5]]


(3, 1)

* $A_{1} \in R^{3\times1}$

![](https://media.giphy.com/media/aGOgOKmyBxCk8/giphy.gif)